apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-app
  namespace: credreg-staging
  labels:
    app: main
spec:
  replicas: 1 # Adjust based on traffic
  selector:
    matchLabels:
      app: main-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: main-app
        app-lang: ruby
    spec:
      priorityClassName: staging-medium
      nodeSelector:
        env: staging
      tolerations:
        - key: "env"
          operator: "Equal"
          value: "staging"
          effect: "NoSchedule"
      serviceAccountName: main-app-service-account
      # DB migrations are handled via a dedicated Job
      containers:
        - name: main-app
          image: 996810415034.dkr.ecr.us-east-1.amazonaws.com/registry:staging
          imagePullPolicy: Always
          command: ["/bin/bash", "-c", "bin/rackup -o 0.0.0.0"]
          env:
            - name: NEW_RELIC_APP_NAME
              value: "Credential Engine Staging"
          ports:
            - containerPort: 9292
          envFrom:
            - secretRef:
                name: app-secrets # DB credentials, APP_KEY, etc.
            - configMapRef:
                name: main-app-config
          resources:
            requests:
              cpu: "500m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: main-app
  namespace: credreg-staging
spec:
  type: ClusterIP
  selector:
    app: main-app
  ports:
    - protocol: TCP
      port: 9292
      targetPort: 9292
