apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elasticsearch
  namespace: credreg-staging
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/auth-type: "basic"
    nginx.ingress.kubernetes.io/auth-secret: "es-basic-auth"
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
    nginx.ingress.kubernetes.io/whitelist-source-range: "181.238.15.41/32,71.212.64.155/32,98.13.197.1/32,98.193.126.147/32"
     # 71.212.64.155  – Rohit
     # 98.13.197.1  – Jenna
     # 98.193.126.147 – Mike P.
     # 98.97.134.76/32 - Ariel
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - es.staging.credentialengineregistry.org
      secretName: staging-credentialengineregistry-org-tls
  rules:
    - host: es.staging.credentialengineregistry.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: elasticsearch
                port:
                  number: 9200
