apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app
  namespace: credreg-staging
  labels:
    app: worker-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: worker-app
        app-lang: ruby
    spec:
      priorityClassName: staging-medium
      nodeSelector:
        env: staging
      tolerations:
        - key: "env"
          operator: "Equal"
          value: "staging"
          effect: "NoSchedule"
      serviceAccountName: main-app-service-account
      containers:
        - name: worker
          image: 996810415034.dkr.ecr.us-east-1.amazonaws.com/registry:staging
          imagePullPolicy: Always
          env:
            - name: NEW_RELIC_APP_NAME
              value: "Credential Engine Staging"
            - name: PATH
              value: "/app/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
          command: ["/bin/bash","-lc"]
          args:
            - |
              if [ -x ./bin/sidekiq ]; then
                ./bin/sidekiq -r ./config/application.rb
              else
                bundle exec sidekiq -r ./config/application.rb
              fi
          envFrom:
            - secretRef:
                name: app-secrets
            - configMapRef:
                name: main-app-config
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"
