apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: skooner-ingress
  namespace: kube-system
  #     # If you use cert-manager for TLS, uncomment the next line and set your issuer
  #     # cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
tls:
    - hosts:
        - status.credentialengineregistry.org
      secretName: skooner-tls
  rules:
      - host: status.credentialengineregistry.org
        http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: skooner
                  port:
                    number: 80