# This file is kept for compatibility.
# The actual runtime configuration is in MetadataRegistry.database_config
# defined in config/application.rb.

default: &default
  adapter: postgresql
  host: <%= ENV['POSTGRESQL_ADDRESS'] %>
  username: <%= ENV['POSTGRESQL_USERNAME'] %>
  database: <%= ENV['POSTGRESQL_DATABASE'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>
  port: <%= ENV.fetch('POSTGRESQL_PORT', 5432) %>
  pool: <%= ENV.fetch('SIDEKIQ_CONCURRENCY', 10).to_i + 1 %>
  encoding: utf8

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

sandbox:
  <<: *default

production:
  <<: *default
