apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-app
  namespace: credreg-prod
  labels:
    app: main
spec:
  replicas: 2
  selector:
    matchLabels:
      app: main-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: main-app
        app-lang: ruby
    spec:
      priorityClassName: prod-high
      nodeSelector:
        env: production
      tolerations:
        - key: "env"
          operator: "Equal"
          value: "production"
          effect: "NoSchedule"
      serviceAccountName: main-app-service-account
      containers:
        - name: main-app
          image: 996810415034.dkr.ecr.us-east-1.amazonaws.com/registry:production
          imagePullPolicy: Always
          command: ["/bin/bash", "-c", "bin/rackup -o 0.0.0.0"]
          env:
            - name: NEW_RELIC_APP_NAME
              value: "Credential Engine Production"
          ports:
            - containerPort: 9292
          envFrom:
            - secretRef:
                name: app-secrets
            - configMapRef:
                name: main-app-config
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1500m"
              memory: "1536Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: main-app
  namespace: credreg-prod
spec:
  type: ClusterIP
  selector:
    app: main-app
  ports:
    - protocol: TCP
      port: 9292
      targetPort: 9292

